services:
  mysql:
    image: mysql:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: picpaydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
